name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test_gmp:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            bazel_config: linux
          - os: macos-latest
            bazel_config: macos_x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Setup Python and Install numpy
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install numpy
        run: python -m pip install numpy

      - name: Build
        run: bazel build -c fastbuild --config ${{ matrix.bazel_config }} --config gmp_backend //...

      - name: Test
        run: bazel test -c fastbuild --config ${{ matrix.bazel_config }} --config gmp_backend --test_output=errors --test_tag_filters -benchmark,-manual,-cuda,-rust //...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --all

      - name: Setup Python for cpplint
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        if: github.event_name == 'pull_request'
        run: git diff --name-only HEAD origin/${{ github.base_ref }} | xargs cpplint --filter=-legal/copyright,-whitespace/line_length,-build/namespaces,-runtime/references

      - name: Run clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: "."
          exclude: "./lib"
          extensions: "h,cc"
          clangFormatVersion: 15
          inplace: True
