name: CI

on: [push, pull_request]

jobs:
  test_gmp:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            bazel_config: linux
          - os: macos-latest
            bazel_config: macos_x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Setup Python and Install numpy
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install numpy
        run: python -m pip install numpy

      - name: Build
        run: bazel build -c fastbuild --config ${{ matrix.bazel_config }} --config gmp_backend //...

      - name: Test
        run: bazel test -c fastbuild --config ${{ matrix.bazel_config }} --config gmp_backend --test_tag_filters -benchmark,-manual,-cuda,-rust //...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.15
        with:
          source: '.'
          exclude: './lib'
          extensions: 'h,cc'
          clangFormatVersion: 15
          inplace: True
